### ISSUE TITLE
typing breaks singledispatch on Python 2

### ISSUE THREAD

**Issue by Wilfred** [python/typing#484]
The following does not work on Python 2:

```python
import typing

from collections import Iterable
from singledispatch import singledispatch

mysum = singledispatch(sum)
mysum.register(Iterable, sum)

print mysum([])
```

Removing the `import typing` fixes the issue. This means that a codebase cannot import typing anywhere without breaking uses of singledispatch.

```
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    print mysum([])
  File "build/bdist.linux-x86_64/egg/singledispatch.py", line 210, in wrapper
  File "build/bdist.linux-x86_64/egg/singledispatch.py", line 191, in dispatch
  File "build/bdist.linux-x86_64/egg/singledispatch.py", line 142, in _find_impl
  File "build/bdist.linux-x86_64/egg/singledispatch.py", line 119, in _compose_mro
  File "build/bdist.linux-x86_64/egg/typing.py", line 1223, in __subclasscheck__
TypeError: Parameterized generics cannot be used with class or instance checks
```

This is [Python bug 28339](https://bugs.python.org/issue28339), which has been fixed in Python 3, but not in the singledispatch library which backports singledispatch to Python 2.

**Comment by gvanrossum** [comment]
I'm confused -- if it should be fixed in the singledispatch backport why
don't you file the bug there?

**Comment by Wilfred** [comment]
Sorry, I was unclear. (I also couldn't find the bugtracker for the singledispatch backport.)

I'm not sure where this should be fixed. As I understand it, typing.py is mutating datastructures in abc.py, so I suspect that's the best place to fix this.

Looking at the relevant code in typing.py:

```python
    def __subclasscheck__(self, cls):
        if self.__origin__ is not None:
            if sys._getframe(1).f_globals['__name__'] not in ['abc', 'functools']:
                raise TypeError("Parameterized generics cannot be used with class "
                                "or instance checks")
            return False
        if self is Generic:
            raise TypeError("Class %r cannot be used with class "
                            "or instance checks" % self)
        return super(GenericMeta, self).__subclasscheck__(cls)
```

Is this only fixing the problem for packages whose name is 'abc' or 'functools'?

I have a kludge that fixes my example script:

```python
import typing

from collections import Iterable

import singledispatch as sd
sd.__name__ = 'functools'

mysum = sd.singledispatch(sum)
mysum.register(Iterable, sum)

print mysum([])
```

This isn't pretty though, and I wonder if general solution is possible inside typing.py.

**Comment by gvanrossum** [comment]
We're going to have to wait until Ivan has time to work on this again.

**Comment by ilevkivskyi** [comment]
@Wilfred 
Unfortunately this is very hard to fix properly in Python 2 (I was thinking about this for long time, but still don't have any satisfactory solution). There is PEP 560, but it will not work for you. In fact it will make the solution for Python 3.7 even better (no ``sys._getframe`` etc.) but will have no effect on Python 2.

The best long-term solution than I can recommend is upgrading to Python 3 (although I know it is not always possible).

**Comment by Wilfred** [comment]
> I also couldn't find a bugtracker for the singledispatch backport.

Aha, it lives here: https://bitbucket.org/ambv/singledispatch/issues

**Comment by ilevkivskyi** [comment]
I am closing this since the ``singledispatch`` on Python 2 part is now fixed by #486. Other cases could be fixed by PEP 560.
